#!/bin/bash

usage() {
    echo "Usage:"
    echo "  podman-ollama [OPTION...] PROMPT"
    echo
    echo "Options:"
    echo "  -g,--gpu   GPU   - Specify a GPU, valid values are AMD and OTHER"
    echo "  -h,--help        - Usage help"
    echo "  -m,--model MODEL - Select non-default model (default: $LLM) "
    echo "  -                - Read from stdin"
    echo
}

cleanup() {
  $PRE $CON exec $CON_PS pkill ollama &
}

server_init() {
  specify_gpu
  select_container_manager
  trap cleanup EXIT

  if [ -e "/dev/dri" ]; then
    ADD="--device /dev/dri"
  fi

  if [ "$GPU" = "OTHER" ]; then
    POST="latest"
  elif [ "$GPU" = "AMD"] || [ -e "/dev/kfd" ]; then
    ADD="$ADD --device /dev/kfd"
    POST="rocm"
  else
    POST="latest"
  fi

  VOL="ollama:/root/.ollama"
  URL="docker.io/ollama/ollama:$POST"
  PRIV="--privileged"
  GPU="--gpus=all"
  CON_PS=$($PRE $CON run --rm $PRIV -d $ADD $GPU -v"$HOME":"$HOME" -v$VOL $URL)
  RET="$?"
  if [ "$RET" -ne 0 ]; then
    echo "$CON_PS"
    exit $RET
  fi
}

select_container_manager() {
  if command -v podman > /dev/null; then
    CON="podman"
  elif command -v docker > /dev/null; then
    CON="docker"
  else
    CON="podman"
  fi
}

specify_gpu() {
  if [ -n "$GPU" ]; then
    shopt -s nocasematch
    case "$GPU" in
      OTHER ) GPU="OTHER";;
      AMD) GPU="AMD";;
      *) echo "Unknown GPU: $GPU"; exit 1;;
    esac

    shopt -u nocasematch
  fi
}

set_initial_vars() {
  LLM="mistral"
  STDIN="false"
}

set -e -o pipefail

set_initial_vars
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage
      exit 0
      ;;
    -g|--gpu)
      GPU="$2"
      shift 2
      ;;
    -m|--model)
      LLM="$2"
      shift 2
      ;;
    -)
      STDIN="true"
      shift 1
      ;;
    -*|--*)
      usage
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      break;
      ;;
  esac
done

server_init

if $STDIN; then
  $PRE $CON exec $CON_PS ollama run $LLM "$(cat /dev/stdin)"
elif [ -n "$1" ]; then
  $PRE $CON exec $CON_PS ollama run $LLM "$1"
else
  $PRE $CON exec -it $CON_PS ollama run $LLM
fi

