#!/bin/bash

cleanup() {
  $PRE $CON exec -it $CON_PS pkill ollama
}

server_init() {
  if [ -e "/dev/dri" ]; then
    ADD="--device /dev/dri"
  fi

  if [ -e "/dev/kfd" ]; then
    ADD="$ADD --device /dev/kfd"
    POST="rocm"
  else
    POST="latest"
  fi

  VOL="ollama:/root/.ollama"
  URL="docker.io/ollama/ollama:$POST"

  # This was introduced as part of ChromeOS support, but there was concerns
  # raised about rootful privileged containers, lets just do this in the rootless
  # case for now.
  if [ "$EUID" -ne 0 ]; then
    PRIV="--privileged"
  fi

  GPU="--gpus=all"
  CON_PS=$($PRE $CON run --rm $PRIV -d $ADD $GPU -v"$HOME":"$HOME" -v$VOL $URL)
  RET="$?"
  if [ "$RET" -ne 0 ]; then
    echo "$CON_PS"
    exit $RET
  fi
}

set -e -o pipefail

if command -v podman > /dev/null; then
  CON="podman"
elif command -v docker > /dev/null; then
  CON="docker"
else
  CON="podman"
fi

trap cleanup EXIT
server_init

if [ -n "$1" ]; then
  $PRE $CON exec -it $CON_PS ollama run llama2 "$1"
else
  $PRE $CON exec -it $CON_PS ollama run llama2
fi

